spring:
  config:
    activate:
      on-profile: dev
    
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: springcloud-config-dev
    
---
spring:
  config:
    activate:
      on-profile: test
  application:
    name: springcloud-config-test
