spring:
  config:
    activate:
      on-profile: dev

---
server:
  port: 8001

# mybatis 读取哪里的实体类，配置文件,mapper文件
mybatis:
  type-aliases-package: org.example.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring 名字，数据源
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: springcloud-provider-dept
  datasource: #哪个数据源，驱动，连接数据库
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useSSL=true&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456

# eureka客户端
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 向7001服务端注册
  instance:
    instance-id: springCloud-provider-dept-8001 #修改服务状态名

# 配置info 监控信息
info:
  app.name: mySpringCloud
# data-center-info:

---
server:
  port: 8001

# mybatis 读取哪里的实体类，配置文件,mapper文件
mybatis:
  type-aliases-package: org.example.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring 名字，数据源
spring:
  config:
    activate:
      on-profile: test
  application:
    name: springcloud-provider-dept
  datasource: #哪个数据源，驱动，连接数据库
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useSSL=true&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456

# eureka客户端
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 向7001服务端注册
  instance:
    instance-id: springCloud-provider-dept-8001 #修改服务状态名

# 配置info 监控信息
info:
  app.name: mySpringCloud
# data-center-info: