spring:
  config:
    activate:
      on-profile: dev

---
server:
  port: 7001

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: springcloud-provider-eureka-dev

# eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己,默认true
    fetch-registry: false # fetch-registry false则表示本服务为注册中心
    service-url: #监控页面地址 参考this.serviceUrl.put("defaultZone", "http://localhost:8761/eureka/");
      defaultZone: http://localhost:7002/eureka/，http://localhost:7003/eureka/ # 这个,不知道会不会有问题
      
---
server:
  port: 7001

spring:
  config:
    activate:
      on-profile: test
  application:
    name: springcloud-provider-eureka-test

# eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己,默认true
    fetch-registry: false # fetch-registry false则表示本服务为注册中心
    service-url: #监控页面地址 参考this.serviceUrl.put("defaultZone", "http://localhost:8761/eureka/");
      defaultZone: http://localhost:7002/eureka/，http://localhost:7003/eureka/